spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/specifications
    username: postgres
    password: DoNotUseMeInProduction!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    show-sql: true
  flyway:
    baseline-on-migrate: true
